---
# tasks file for containerd | EL Family

- name: "EL Family | Downloading/Extracting archive for {{ containerd_app }} {{ containerd_version }} to {{ containerd_bin_path }}"
  ansible.builtin.unarchive:
    src: "{{ containerd_dl_url }}"
    dest: "{{ containerd_bin_path }}"
    mode: "{{ containerd_files_mode }}"
    owner: "{{ containerd_files_owner }}"
    group: "{{ containerd_files_group }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: "EL Family | Provision systemd service for {{ containerd_app }} as {{ containerd_systemd_template_out_dir }}/{{ containerd_systemd_template_out_file }}"
  ansible.builtin.template:
    src: "{{ containerd_systemd_template_in_file }}"
    dest: "{{ containerd_systemd_template_out_dir }}/{{ containerd_systemd_template_out_file }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - "Enable {{ containerd_app }} systemd service"
    - "Set {{ containerd_app }} systemd service state"
